kubectl create ns multi-1
kubectl create ns multi-2
kubectl create ns multi-3
kubectl create ns multi-4
kubectl create ns multi-5
kubectl create ns multi-6
kubectl create ns multi-7
kubectl create ns multi-8
kubectl create ns multi-9
kubectl create ns multi-10
kubectl create ns multi-11
kubectl create ns multi-12
kubectl create ns multi-13
kubectl create ns multi-14
kubectl create ns multi-15
kubectl create ns multi-16
kubectl create ns multi-17
kubectl create ns multi-18
kubectl create ns multi-19
kubectl create ns multi-20
kubectl create ns multi-21
kubectl create ns multi-22
kubectl create ns multi-23
kubectl create ns multi-24
kubectl create ns multi-25
kubectl create ns multi-26
kubectl create ns multi-27
kubectl create ns multi-28
kubectl create ns multi-29
kubectl create ns multi-30
