kubectl delete ns multi-1
kubectl delete ns multi-2
kubectl delete ns multi-3
kubectl delete ns multi-4
kubectl delete ns multi-5
kubectl delete ns multi-6
kubectl delete ns multi-7
kubectl delete ns multi-8
kubectl delete ns multi-9
kubectl delete ns multi-10
kubectl delete ns multi-11
kubectl delete ns multi-12
kubectl delete ns multi-13
kubectl delete ns multi-14
kubectl delete ns multi-15
kubectl delete ns multi-16
kubectl delete ns multi-17
kubectl delete ns multi-18
kubectl delete ns multi-19
kubectl delete ns multi-20
kubectl delete ns multi-21
kubectl delete ns multi-22
kubectl delete ns multi-23
kubectl delete ns multi-24
kubectl delete ns multi-25
kubectl delete ns multi-26
kubectl delete ns multi-27
kubectl delete ns multi-28
kubectl delete ns multi-29
kubectl delete ns multi-30
